### ISSUE TITLE
CentOS7: Vagrant: node-svm インストール時のエラー

### ISSUE THREAD

**Issue by kesuiket** [super-true/Learning-node-js#10]
```bash
$ npm install node-svm
```

エラー

```bash
In file included from ../src/addon.cc:3:0:
../src/node-svm/node-svm.h:10:40: 致命的エラー: ../../node_modules/nan/nan.h: そのようなファイルやディレクトリはありません
 #include "../../node_modules/nan/nan.h"
                                        ^
コンパイルを停止しました。
make: *** [Release/obj.target/addon/src/addon.o] エラー 1
make: ディレクトリ `/var/www/html/node_modules/node-svm/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/node_modules/node-svm
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.1/bin/npm" "install" "node-svm"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-svm@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-svm@2.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-svm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-svm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log
```

**Comment by kesuiket** [comment]
-g オプションを忘れてた。

```bash
$ npm install -g node-svm
```

新たなエラー。

```bash
> node-svm@2.1.6 install /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-svm
> node-gyp rebuild

sh: node-gyp: コマンドが見つかりません
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.1/bin/npm" "install" "-g" "node-svm"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-svm@2.1.6 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-svm@2.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-svm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-svm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log
```

**Comment by kesuiket** [comment]
node-svm じゃなくて svm だった・・・。

```
$ npm install -g svm
```

解決。

**Comment by kesuiket** [comment]
再開

**Comment by kesuiket** [comment]
Ubuntu では `build-essential` がないと `node-gyp` が動かないとか。

- [Ubuntu 13.10 の npm install で node-gyp rebuild が失敗する](http://blog.yug1224.com/2014/01/27/npm-error/)

で、CentOSでそれにあたるものは？

- [Ubuntu の build-essentials 的なことを yum でやりたいときの方法](http://blog.64p.org/entry/2013/07/22/142457)

これを参考に↓を叩く

```bash
$ sudo yum groupinstall "Development Tools"
$ sudo yum install kernel-devel kernel-headers
```

**Comment by kesuiket** [comment]
`-g` オプションを与えない場合は無事インストールできる。
それでは意味がないけど。

**Comment by kesuiket** [comment]
`sudo` をつけずにインストールで `-g` ありでも無事インストール。

```bash
$ npm install -g node-svm

$ node-svm -v
2.1.6
```

解決。
