### ISSUE TITLE
CasperJS のエラー

### ISSUE THREAD

**Issue by kesuiket** [super-true/Learning-node-js#6]
```bash
Error: Cannot find module 'casper'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/PATH/TO/PROGRAM)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by kesuiket** [comment]
コマンドを間違えてた・・・。
```bash
# ×
node file.js

# ○
casperjs file.js
```

**Comment by kesuiket** [comment]
終了
