### ISSUE TITLE
CentOS7: Vagrant: MongoDB インストール時のエラー

### ISSUE THREAD

**Issue by kesuiket** [super-true/Learning-node-js#7]
```bash
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: 致命的エラー: gssapi/gssapi.h: そのようなファイルやディレクトリはありません
 #include <gssapi/gssapi.h>
                           ^
コンパイルを停止しました。
make: *** [Release/obj.target/kerberos/lib/kerberos.o] エラー 1
make: ディレクトリ `/home/vagrant/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
mongodb@2.0.46 node_modules/mongodb
├── es6-promise@2.1.1
├── readable-stream@1.0.31 (core-util-is@1.0.1, string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1)
└── mongodb-core@1.2.19 (bson@0.4.19, kerberos@0.0.15)
```

**Comment by kesuiket** [comment]
以下を参考にして解決。

[CentOS7 MongoDBのインストール](http://qiita.com/daskepon/items/aa93f8955407da0cb896)
