### ISSUE TITLE
CentOS7: Vagrant: npm install mongodb でのエラー

### ISSUE THREAD

**Issue by kesuiket** [super-true/Learning-node-js#9]
```bash
$ npm install mongodb
```

```bash
make: ディレクトリ `/var/www/html/ch7/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build' に入ります
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: 致命的エラー: gssapi/gssapi.h: そのようなファイルやディレクトリはありません
 #include <gssapi/gssapi.h>
                           ^
コンパイルを停止しました。
make: *** [Release/obj.target/kerberos/lib/kerberos.o] エラー 1
make: ディレクトリ `/var/www/html/ch7/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/ch7/bot/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
mecab-lite@0.0.8 no
```

**Comment by kesuiket** [comment]
Ubuntu で同様のエラーの記事

- [npm install mongoose causes gyp and kerberos errors (gssapi/gssapi.h file not found)](http://stackoverflow.com/questions/32919589/npm-install-mongoose-causes-gyp-and-kerberos-errors-gssapi-gssapi-h-file-not-fo)

```bash
apt-get install libkrb5-dev
```

`libkrb5-dev` が必要らしいけど CentOS ではそれが何に当たるのか。

- [Redhat系(CentOS/Scientific Linux等)でGitlab7.5から7.6に上げる際に必要なlibkrb5-devについて](http://www.nanao-a.com/blog/html/2015/01/19/gitlab7_5_for_7_6.html)

```bash
$ yum install krb5-devel
```

ということらしい。

```bash
$ npm install mongodb
```

無事インストールできて解決。
